const categoryList = {
	Ketchup: true,
	Pickles: true,
	Relish: true,
	Mustard: true,
	Mayonnaise: true,
	'Peanut Butter': true,
	Honey: true,
	Jam: true,
	Jelly: true,
	'Salad Dressing': true,
	Marinades: true,
	'Barbecue Sauce': true,
	Croutons: true,
	Eggs: true,
	Butter: true,
	'Cottage Cheese': true,
	Milk: true,
	Yogurt: true,
	'Sour Cream': true,
	'Whipped Cream': true,
	'Cream Cheese': true,
	'Cookie Dough': true,
	'Pizza Dough': true,
	Popcorn: true,
	Chips: true,
	Nuts: true,
	Tea: true,
	Coffee: true,
	Napkins: true,
	Foil: true,
	'Paper Plates': true,
	'Liquid Dish Soap': true,
	'Toilet Paper': true,
	'Paper Towels': true,
	'Dishwasher Soad': true,
	Razors: true,
	'Shave Cream': true,
	Deodorant: true,
	Lotion: true,
	Toothpaste: true,
	'Shampoo / Conditioner': true,
};

export default categoryList;
